# Data Cleaning

In [405]:
import pandas as pd
import numpy as np

In [406]:
# import csv
data = pd.read_csv("/home/cate/Cate/DSI/DSI_trick_challenge/final.csv",header = 0)

In [407]:
data.head()

,location,price,floor_size,bathrooms,bedrooms,parking
0,"['Green Point', 'Zonnebloem', 'Constantia', 'G...",['\n\n R 8\xa0750\xa0000\n '...,"['175 m²', None, '253 m²', '175 m²', '139 m²',...","['2', '1', '3', '2', '2.5', '3', '1', '1', '1'...","['2', '2', '3', '2', '3', '3', '2', '1', '3', ...","['2', '1', '2', '2', '3', '3', '2', '1', '1', ..."
1,"['Sea Point', 'Tokai', 'Camps Bay', 'Kenilwort...",['\n\n R 15\xa0999\xa0000\n ...,"['300 m²', '1 085 m²', '659 m²', '2 842 m²', '...","['4.5', '3', '3.5', '8', '4.5', '2', '1', '1',...","['4', '4', '4', '8', '4', '2', '3', '2', '3', ...","['2', '5', '4', '11', '2', '1', '6', None, '2'..."
2,"['Observatory', 'Green Point', 'Diep River', '...",['\n\n R 1\xa0900\xa0000\n '...,"['65 m²', None, '651 m²', '73 m²', None, '93 m...","['2', '7', '2', '1', None, '2', '2', '2', '2',...","['2', '6', '4', '2', None, '2', '3', '2', '2',...","['1', '3', '1', '2', None, '2', None, '2', '1'..."
3,"['Bantry Bay', 'Bantry Bay', 'Tokai', 'Cape To...",['\n\n R 18\xa0995\xa0000\n ...,"['159 m²', '144 m²', '1 001 m²', '71 m²', '61 ...","['2', '3', '2.5', '1', '1', '2', '3', '3', '1'...","['2', '3', '3', '1', '1', '3', '3', '3', '1', ...","['1', '2', '6', '1', '2', '1', '1', '2', '1', ..."
4,"['Ottery', 'Cape Town City Centre', 'Steenberg...",['\n\n R 5\xa0800\xa0000\n '...,"['803 m²', '191 m²', '747 m²', '85 m²', '86 m²...","['10', '2', '4', '1', '2', '2.5', '1', '2', '4...","['10', '2', '4', '2', '2', '2', '3', '3', '4',...","['8', '2', '6', '1', '2', '2', '2', '2', '4', ..."

In [408]:
data = data.astype(object)

In [409]:
cols = data.columns
cols

Index(['location', 'price', 'floor_size', 'bathrooms', 'bedrooms', 'parking'], dtype='object')

In [410]:
datas = data.unstack().str.strip('[]').str.split(', ', expand=True)

In [411]:
datas

                                   0                        1   \
location 0              'Green Point'             'Zonnebloem'
         1                'Sea Point'                  'Tokai'
         2              'Observatory'            'Green Point'
         3               'Bantry Bay'             'Bantry Bay'
         4                   'Ottery'  'Cape Town City Centre'
         5            'Wynberg Upper'  'Cape Town City Centre'
         6    'Cape Town City Centre'            'Meadowridge'
         7               'Constantia'              'Claremont'
         8               'Kenilworth'              'Vredehoek'
         9            'Wynberg Upper'               'Fresnaye'
         10               'Sea Point'                'Gardens'
         11               'Claremont'          'Wynberg Upper'
         12               'Vredehoek'             'Constantia'
         13           'Wynberg Upper'             'Constantia'
         14              'Constantia'          'Tamboerskloof'
         15              'Kenilworth'       'Harfield Village'
         16          'Marina Da Gama'              'Newfields'
         17               'Bergvliet'             'Constantia'
         18                'Newlands'              'Vredehoek'
         19              'Bantry Bay'             'Rondebosch'
         20               'Sea Point'              'Claremont'
         21               'Sea Point'        'Claremont Upper'
         22              'Muizenberg'  'Cape Town City Centre'
         23              'Constantia'             'Diep River'
         24             'Green Point'                'Wynberg'
         25              'Bantry Bay'              'Plumstead'
         26         'Claremont Upper'                'Wynberg'
         27           'Mouille Point'             'Kenilworth'
         28                'Lakeside'        'Claremont Upper'
         29                'Maitland'              'Sea Point'
...                               ...                      ...
parking  368                      '8'                      '4'
         369                      '2'                     None
         370                      '3'                      '3'
         371                      '1'                     None
         372                      '1'                      '1'
         373                     None                      '2'
         374                      '2'                      '1'
         375                      '1'                      '6'
         376                      '2'                      '2'
         377                      '1'                      '2'
         378                      '6'                     None
         379                     None                      '1'
         380                      '2'                      '1'
         381                     None                     None
         382                      '1'                      '2'
         383                      '4'                     None
         384                     None                      '4'
         385                      '2'                      '2'
         386                      '1'                     None
         387                      '3'                      '3'
         388                      '1'                     None
         389                     None                      '1'
         390                      '1'                      '1'
         391                      '1'                      '2'
         392                      '2'                     None
         393                      '3'                      '2'
         394                      '1'                      '3'
         395                      '2'                     None
         396                      '1'                     None
         397                     None                      '2'

                                   2                             3   \
location 0               'Constantia'                 'Green Point'
         1                'Camps Bay'            'Kenilworth Upper'
         2               'Diep River'                    'Lakeside'
         3                    'Tokai'       'Cape Town City Centre'
         4    'Steenberg Golf Estate'                  'Diep River'
         5              'Green Point'                  'Constantia'
         6                'Sea Point'                    'Fresnaye'
         7          'Claremont Upper'                    'Lakeside'
         8               'Zonnebloem'       'Cape Town City Centre'
         9              'Green Point'                   'Woodstock'
         10              'Muizenberg'                 'Green Point'
         11                 'Gardens'                 'Oranjezicht'
         12              'Waterfront'                   'Sea Point'
         13   'Cape Town City Centre'                 'Oranjezicht'
         14   'Cape Town City Centre'                   'Pinelands'
         15               'Sea Point'       'Cape Town City Centre'
         16                'Rosebank'             'Claremont Upper'
         17         'Claremont Upper'                   'Claremont'
         18   'Cape Town City Centre'                    'Rosebank'
         19               'Sea Point'                    'Fresnaye'
         20                 'Clifton'                 'Green Point'
         21           'Walmer Estate'  'Stonehurst Mountain Estate'
         22                 'Gardens'                    'Newlands'
         23               'Sea Point'                  'Rondebosch'
         24   'Cape Town City Centre'                 'Oranjezicht'
         25               'Sea Point'                  'Waterfront'
         26             'Observatory'                  'Kirstenhof'
         27                'Newlands'                  'Diep River'
         28              'Heathfield'               'Tamboerskloof'
         29              'Waterfront'               'Tamboerskloof'
...                               ...                           ...
parking  368                      '2'                           '1'
         369                      '1'                           '1'
         370                      '1'                           '1'
         371                     None                           '1'
         372                     None                           '2'
         373                     None                          None
         374                      '4'                           '1'
         375                      '1'                           '2'
         376                      '2'                           '7'
         377                     None                           '1'
         378                      '3'                           '1'
         379                      '2'                           '1'
         380                      '1'                          None
         381                      '1'                           '1'
         382                      '1'                           '2'
         383                      '1'                           '6'
         384                     None                           '1'
         385                      '1'                           '1'
         386                      '2'                           '2'
         387                      '1'                           '2'
         388                     None                           '1'
         389                      '2'                          None
         390                      '1'                           '1'
         391                     None                           '1'
         392                      '1'                           '1'
         393                      '4'                           '1'
         394                     None                           '2'
         395                      '1'                          None
         396                     None                           '1'
         397                      '1'                           '2'

                                   4                             5   \
location 0               'Kenilworth'                  'Constantia'
         1                  'Gardens'                   'Sea Point'
         2                  'Wynberg'                  'Rondebosch'
         3             'De Waterkant'                 'Green Point'
         4          'Claremont Upper'                   'Sea Point'
         5                'Camps Bay'                    'Rosebank'
         6               'Muizenberg'                   'Sea Point'
         7                 'Newlands'                 'Oranjezicht'
         8               'Kenilworth'                   'Bergvliet'
         9               'Rondebosch'                   'Sea Point'
         10               'Woodstock'                   'Vredehoek'
         11                'Newlands'                     'Wynberg'
         12               'Mountview'            'Kenilworth Upper'
         13               'Camps Bay'             'Claremont Upper'
         14             'Observatory'  'Stonehurst Mountain Estate'
         15              'Kensington'                'Kreupelbosch'
         16   'Cape Town City Centre'                  'Waterfront'
         17                  'Ottery'                  'Constantia'
         18         'Claremont Upper'       'Cape Town City Centre'
         19               'Claremont'                   'Claremont'
         20              'Bantry Bay'                     'Gardens'
         21               'Sea Point'               'Tamboerskloof'
         22               'Woodstock'                  'Rondebosch'
         23              'Waterfront'                  'Waterfront'
         24              'Muizenberg'                      'Kenwyn'
         25               'Camps Bay'                   'Woodstock'
         26         'Claremont Upper'                   'Sea Point'
         27             'Oranjezicht'                     'Gardens'
         28               'Woodstock'                  'Waterfront'
         29                  'Wetton'                   'Higgovale'
...                               ...                           ...
parking  368                      '4'                           '2'
         369                      '2'                           '2'
         370                      '1'                           '2'
         371                      '3'                           '1'
         372                      '1'                          None
         373                      '2'                          None
         374                      '2'                           '1'
         375                      '4'                           '1'
         376                      '1'                           '1'
         377                     None                           '2'
         378                     None                          None
         379                      '1'                           '2'
         380                      '1'                           '2'
         381                      '1'                           '1'
         382                      '2'                           '1'
         383                     '12'                           '2'
         384                     None                           '1'
         385                      '2'                          None
         386                      '1'                           '1'
         387                      '1'                           '2'
         388                      '2'                           '3'
         389                      '1'                           '1'
         390                     None                           '2'
         391                      '1'                          None
         392                      '2'                           '2'
         393                      '1'                          None
         394                      '1'                           '1'
         395                      '1'                           '2'
         396                      '2'                          None
         397                      '2'                           '1'

                                   6                        7   \
location 0                'Pinelands'          'Wynberg Upper'
         1                 'Parkwood'             'Bantry Bay'
         2                'Pinelands'              'Foreshore'
         3            'Walmer Estate'  'Cape Town City Centre'
         4                'Plumstead'                'Retreat'
         5                'Sea Point'             'Constantia'
         6              'Oranjezicht'            'Green Point'
         7                'Woodstock'               'Newlands'
         8                'Camps Bay'              'Claremont'
         9                'Camps Bay'             'Constantia'
         10              'Diep River'              'Plumstead'
         11               'Woodstock'              'Plumstead'
         12                 'Gardens'  'Cape Town City Centre'
         13                'Lakeside'        'Claremont Upper'
         14         'Claremont Upper'              'Pinelands'
         15               'Sea Point'            'Observatory'
         16                 'Gardens'               'Rosebank'
         17             'Oranjezicht'       'Kenilworth Upper'
         18             'Observatory'               'Newlands'
         19               'Sea Point'              'Plumstead'
         20               'Vredehoek'               'Newlands'
         21              'Kenilworth'              'Woodstock'
         22        'Kenilworth Upper'              'Sea Point'
         23               'Sea Point'                'Clifton'
         24             'Lotus River'               'Newlands'
         25           'Tamboerskloof'            'Observatory'
         26              'Salt River'              'Claremont'
         27        'Three Anchor Bay'              'Sea Point'
         28              'Kirstenhof'  'Cape Town City Centre'
         29   'Cape Town City Centre'        'Claremont Upper'
...                               ...                      ...
parking  368                      '1'                      '2'
         369                      '2'                     None
         370                     None                      '1'
         371                      '1'                     None
         372                      '1'                      '1'
         373                      '2'                      '2'
         374                      '2'                      '1'
         375                      '1'                      '3'
         376                     None                     None
         377                      '5'                      '2'
         378                      '1'                      '1'
         379                      '2'                      '1'
         380                     None                      '1'
         381                      '2'                      '1'
         382                      '2'                     None
         383                     None                      '1'
         384                      '4'                     None
         385                      '1'                      '1'
         386                      '2'                     None
         387                      '1'                     None
         388                     None                      '1'
         389                     None                     None
         390                      '2'                     None
         391                      '1'                     None
         392                      '1'                     None
         393                     None                      '1'
         394                     None                      '1'
         395                      '1'                      '3'
         396                     None                     None
         397                     '12'                      '2'

                                   8                        9   ...  \
location 0            'Tamboerskloof'              'Pinelands'  ...
         1                'Sea Point'             'Kenilworth'  ...
         2               'Rondebosch'             'Waterfront'  ...
         3              'Oranjezicht'              'Foreshore'  ...
         4                'Llandudno'  'Cape Town City Centre'  ...
         5               'Salt River'              'Sea Point'  ...
         6                  'Clifton'  'Cape Town City Centre'  ...
         7                'Claremont'              'Sea Point'  ...
         8    'Cape Town City Centre'  'Cape Town City Centre'  ...
         9              'Green Point'             'Diep River'  ...
         10         'Claremont Upper'                'Gardens'  ...
         11               'Pinelands'                'Gardens'  ...
         12              'Rondebosch'              'Plumstead'  ...
         13             'Green Point'              'Sea Point'  ...
         14          'Marina Da Gama'            'Oranjezicht'  ...
         15             'Oranjezicht'                'Gardens'  ...
         16              'Waterfront'              'Sea Point'  ...
         17           'Mouille Point'             'Rondebosch'  ...
         18               'Plumstead'        'Claremont Upper'  ...
         19               'Foreshore'              'Woodstock'  ...
         20               'Bergvliet'              'Sea Point'  ...
         21             'Green Point'              'Sea Point'  ...
         22             'Green Point'             'Ocean View'  ...
         23               'Claremont'            'Green Point'  ...
         24                'Thornton'            'Green Point'  ...
         25                 'Gardens'               'Lakeside'  ...
         26               'Woodstock'  'Cape Town City Centre'  ...
         27                'Newlands'             'Kenilworth'  ...
         28             'Green Point'            'Green Point'  ...
         29        'Three Anchor Bay'                'Mowbray'  ...
...                               ...                      ...  ...
parking  368                      '2'                      '1'  ...
         369                      '1'                     None  ...
         370                      '1'                      '2'  ...
         371                      '2'                      '1'  ...
         372                      '1'                     None  ...
         373                     None                      '4'  ...
         374                      '2'                      '1'  ...
         375                     None                      '6'  ...
         376                     None                      '2'  ...
         377                      '5'                      '4'  ...
         378                      '1'                      '2'  ...
         379                      '2'                      '1'  ...
         380                      '2'                      '4'  ...
         381                      '1'                      '1'  ...
         382                      '1'                      '1'  ...
         383                      '4'                     None  ...
         384                      '1'                     None  ...
         385                      '1'                      '1'  ...
         386                      '1'                      '1'  ...
         387                     None                      '3'  ...
         388                      '2'                      '1'  ...
         389                      '1'                      '2'  ...

In [412]:
un_data = datas.unstack()

In [413]:
df = un_data.reset_index()

In [414]:
new_data = df.T

In [415]:
new_data.columns = new_data.iloc[0]
new_data

('index', '')                 location  \
index                         location
0     0                  'Green Point'
      1                    'Sea Point'
      2                  'Observatory'
      3                   'Bantry Bay'
      4                       'Ottery'
      5                'Wynberg Upper'
      6        'Cape Town City Centre'
      7                   'Constantia'
      8                   'Kenilworth'
      9                'Wynberg Upper'
      10                   'Sea Point'
      11                   'Claremont'
      12                   'Vredehoek'
      13               'Wynberg Upper'
      14                  'Constantia'
      15                  'Kenilworth'
      16              'Marina Da Gama'
      17                   'Bergvliet'
      18                    'Newlands'
      19                  'Bantry Bay'
      20                   'Sea Point'
      21                   'Sea Point'
      22                  'Muizenberg'
      23                  'Constantia'
      24                 'Green Point'
      25                  'Bantry Bay'
      26             'Claremont Upper'
      27               'Mouille Point'
      28                    'Lakeside'
...                                ...
20    368      'Cape Town City Centre'
      369                  'Woodstock'
      370                  'Sea Point'
      371                  'Camps Bay'
      372                  'Sea Point'
      373                  'Pinelands'
      374                 'Rondebosch'
      375                  'Sea Point'
      376      'Cape Town City Centre'
      377                  'Plumstead'
      378                  'Camps Bay'
      379               'Pelican Park'
      380                  'Woodstock'
      381                   'Newlands'
      382               'De Waterkant'
      383                  'Sea Point'
      384                'Green Point'
      385                 'Kenilworth'
      386      'Cape Town City Centre'
      387                  'Pinelands'
      388               'De Waterkant'
      389               'Pelican Park'
      390                 'Diep River'
      391                  'Sea Point'
      392      'Cape Town City Centre'
      393                  'Vredehoek'
      394                  'Lansdowne'
      395                 'Zonnebloem'
      396               'De Waterkant'
      397                         None

('index', '')                                           price  floor_size  \
index                                                   price  floor_size
0     0         '\n\n            R 8\xa0750\xa0000\n        '    '175 m²'
      1        '\n\n            R 15\xa0999\xa0000\n        '    '300 m²'
      2         '\n\n            R 1\xa0900\xa0000\n        '     '65 m²'
      3        '\n\n            R 18\xa0995\xa0000\n        '    '159 m²'
      4         '\n\n            R 5\xa0800\xa0000\n        '    '803 m²'
      5         '\n\n            R 5\xa0550\xa0000\n        '    '918 m²'
      6         '\n\n            R 2\xa0290\xa0000\n        '    '106 m²'
      7        '\n\n            R 19\xa0900\xa0000\n        '  '1 437 m²'
      8         '\n\n            R 1\xa0875\xa0000\n        '     '82 m²'
      9         '\n\n            R 2\xa0800\xa0000\n        '    '712 m²'
      10        '\n\n            R 4\xa0250\xa0000\n        '    '178 m²'
      11        '\n\n            R 1\xa0699\xa0000\n        '    '130 m²'
      12        '\n\n            R 1\xa0450\xa0000\n        '     '42 m²'
      13        '\n\n            R 3\xa0750\xa0000\n        '    '100 m²'
      14        '\n\n            R 5\xa0950\xa0000\n        '  '1 561 m²'
      15        '\n\n            R 1\xa0850\xa0000\n        '    '104 m²'
      16        '\n\n            R 1\xa0590\xa0000\n        '    '174 m²'
      17        '\n\n            R 3\xa0895\xa0000\n        '    '862 m²'
      18        '\n\n            R 5\xa0900\xa0000\n        '    '628 m²'
      19       '\n\n            R 13\xa0000\xa0000\n        '    '149 m²'
      20        '\n\n            R 2\xa0150\xa0000\n        '     '81 m²'
      21        '\n\n            R 2\xa0800\xa0000\n        '        None
      22        '\n\n            R 2\xa0793\xa0000\n        '    '402 m²'
      23        '\n\n            R 5\xa0150\xa0000\n        '    '792 m²'
      24        '\n\n            R 1\xa0750\xa0000\n        '     '51 m²'
      25       '\n\n            R 12\xa0950\xa0000\n        '    '151 m²'
      26        '\n\n            R 1\xa0595\xa0000\n        '     '74 m²'
      27        '\n\n            R 7\xa0500\xa0000\n        '     '91 m²'
      28        '\n\n            R 3\xa0499\xa0000\n        '    '659 m²'
...                                                       ...         ...
20    368       '\n\n            R 8\xa0850\xa0000\n        '    '297 m²'
      369       '\n\n            R 1\xa0695\xa0000\n        '     '57 m²'
      370       '\n\n            R 2\xa0900\xa0000\n        '     '87 m²'
      371      '\n\n            R 24\xa0975\xa0000\n        '    '747 m²'
      372       '\n\n            R 8\xa0700\xa0000\n        '        None
      373            '\n\n            R 617\xa0079\n        '     '20 m²'
      374       '\n\n            R 1\xa0985\xa0000\n        '        None
      375       '\n\n            R 4\xa0250\xa0000\n        '    '178 m²'
      376       '\n\n            R 1\xa0750\xa0000\n        '     '57 m²'
      377       '\n\n            R 2\xa0295\xa0000\n        '    '497 m²'
      378      '\n\n            R 33\xa0925\xa0000\n        '    '456 m²'
      379            '\n\n            R 440\xa0000\n        '        None
      380       '\n\n            R 1\xa0350\xa0000\n        '    '120 m²'
      381       '\n\n            R 3\xa0950\xa0000\n        '    '534 m²'
      382       '\n\n            R 2\xa0950\xa0000\n        '     '50 m²'
      383       '\n\n            R 2\xa0880\xa0000\n        '     '47 m²'
      384       '\n\n            R 3\xa0495\xa0000\n        '    '110 m²'
      385       '\n\n            R 3\xa0590\xa0000\n        '    '247 m²'
      386       '\n\n            R 2\xa0400\xa0000\n        '     '63 m²'
      387            '\n\n            R 595\xa0000\n        '        None
      388       '\n\n            R 4\xa0950\xa0000\n        '     '73 m²'
      389            '\n\n            R 850\xa0000\n        '    '201 m²'
      390       '\n\n            R 2\xa0342\xa0107\n        '        None
      391       '\n\n            R 1\xa0275\xa0000\n        '     '24 m²'
      392       '\n\n            R 1\xa0925\xa0000\n        '     '35 m²'
      393       '\n\n            R 2\xa0995\xa0000\n        '    '100 m²'
      394       '\n\n            R 3\xa0200\xa0000\n        '    '934 m²'
      395            '\n\n            R 950\xa0000\n        '        None
      396       '\n\n            R 2\xa0999\xa0000\n        '        None
      397                                                None        None

('index', '')  bathrooms  bedrooms  parking
index          bathrooms  bedrooms  parking
0     0              '2'       '2'      '2'
      1            '4.5'       '4'      '2'
      2              '2'       '2'      '1'
      3              '2'       '2'      '1'
      4             '10'      '10'      '8'
      5              '4'       '4'      '2'
      6            '1.5'       '1'      '1'
      7            '5.5'       '5'      '7'
      8            '1.5'       '2'      '2'
      9              '3'       '3'      '4'
      10             '2'       '2'      '2'
      11             '1'       '2'      '2'
      12             '1'       '1'      '1'
      13             '2'       '2'      '2'
      14           '2.5'       '4'      '5'
      15             '1'       '2'      '2'
      16             '2'       '2'      '2'
      17             '3'       '3'      '7'
      18           '2.5'       '3'      '2'
      19             '2'       '2'      '1'
      20             '1'       '2'     None
      21             '2'       '2'     None
      22             '2'       '4'     None
      23             '2'       '4'      '4'
      24             '1'      None     None
      25             '2'       '3'      '1'
      26             '1'       '2'      '1'
      27             '1'       '2'      '1'
      28             '2'       '3'      '5'
...                  ...       ...      ...
20    368          '3.5'       '3'      '2'
      369            '1'       '1'      '1'
      370            '1'       '2'     None
      371            '4'       '4'      '2'
      372            '2'       '2'      '2'
      373            '1'       '1'      '1'
      374           None      None     None
      375            '2'       '2'     None
      376            '1'       '1'      '1'
      377          '2.5'       '4'      '6'
      378          '3.5'       '3'     None
      379            '1'       '2'     None
      380            '1'       '2'     None
      381            '1'       '3'      '6'
      382            '1'       '1'      '1'
      383            '1'       '2'      '1'
      384            '1'       '3'      '2'
      385            '2'       '3'      '3'
      386            '2'       '2'     None
      387            '1'      None     None
      388            '2'       '2'      '2'
      389           None      None     None
      390            '1'       '2'      '1'
      391            '1'       '1'     None
      392            '1'       '1'      '1'
      393            '1'       '3'     None
      394           None      None     None
      395            '1'       '1'     None
      396            '1'       '1'      '1'
      397           None      None     None

[8359 rows x 6 columns]

In [416]:
new_data.reset_index(drop=True, inplace=True)

In [417]:
final = new_data.iloc[1:]

In [418]:
final.shape

(8358, 6)

In [419]:
final.dtypes

(index, )
location      object
price         object
floor_size    object
bathrooms     object
bedrooms      object
parking       object
dtype: object

In [420]:
final['bathrooms'] = final['bathrooms'].apply(lambda x: str(x).replace("'", "").strip())

/home/cate/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [421]:
final['bedrooms'] = final['bedrooms'].apply(lambda x: str(x).replace("'", "").strip())
final['parking'] = final['parking'].apply(lambda x: str(x).replace("'", "").strip())
final['location'] = final['location'].apply(lambda x: str(x).replace("'", "").strip())
final['floor_size'] = final['floor_size'].apply(lambda x: str(x).replace("m²", "").strip())

/home/cate/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/cate/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/home/cate/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/cate/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [422]:
final['floor_size'] = final['floor_size'].apply(lambda x: str(x).replace("'", "").strip())

/home/cate/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [432]:
final['price'] = final['price'].apply(lambda x: str(x).replace("xa0", "").strip())

/home/cate/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [444]:
final['price'] = final['price'].apply(lambda x: x.replace("R", "").strip())
final

/home/cate/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

"(index, )",location,price,floor_size,bathrooms,bedrooms,parking
1,Green Point,'\n\n 8\750\000\n ',175,2,2,2
2,Sea Point,'\n\n 15\999\000\n ',300,4.5,4,2
3,Observatory,'\n\n 1\900\000\n ',65,2,2,1
4,Bantry Bay,'\n\n 18\995\000\n ',159,2,2,1
5,Ottery,'\n\n 5\800\000\n ',803,10,10,8
6,Wynberg Upper,'\n\n 5\550\000\n ',918,4,4,2
7,Cape Town City Centre,'\n\n 2\290\000\n ',106,1.5,1,1
8,Constantia,'\n\n 19\900\000\n ',1 437,5.5,5,7
9,Kenilworth,'\n\n 1\875\000\n ',82,1.5,2,2
10,Wynberg Upper,'\n\n 2\800\000\n ',712,3,3,4
11,Sea Point,'\n\n 4\250\000\n ',178,2,2,2
12,Claremont,'\n\n 1\699\000\n ',130,1,2,2
13,Vredehoek,'\n\n 1\450\000\n ',42,1,1,1
14,Wynberg Upper,'\n\n 3\750\000\n ',100,2,2,2
15,Constantia,'\n\n 5\950\000\n ',1 561,2.5,4,5
16,Kenilworth,'\n\n 1\850\000\n ',104,1,2,2
17,Marina Da Gama,'\n\n 1\590\000\n ',174,2,2,2
18,Bergvliet,'\n\n 3\895\000\n ',862,3,3,7
19,Newlands,'\n\n 5\900\000\n ',628,2.5,3,2
20,Bantry Bay,'\n\n 13\000\000\n ',149,2,2,1
21,Sea Point,'\n\n 2\150\000\n ',81,1,2,None
22,Sea Point,'\n\n 2\800\000\n ',None,2,2,None
23,Muizenberg,'\n\n 2\793\000\n ',402,2,4,None
24,Constantia,'\n\n 5\150\000\n ',792,2,4,4
25,Green Point,'\n\n 1\750\000\n ',51,1,None,None
26,Bantry Bay,'\n\n 12\950\000\n ',151,2,3,1
27,Claremont Upper,'\n\n 1\595\000\n ',74,1,2,1
28,Mouille Point,'\n\n 7\500\000\n ',91,1,2,1
29,Lakeside,'\n\n 3\499\000\n ',659,2,3,5
30,Maitland,'\n\n 810\000\n ',54,1,2,None
...,...,...,...,...,...,...
8329,Cape Town City Centre,'\n\n 8\850\000\n ',297,3.5,3,2
8330,Woodstock,'\n\n 1\695\000\n ',57,1,1,1
8331,Sea Point,'\n\n 2\900\000\n ',87,1,2,None
8332,Camps Bay,'\n\n 24\975\000\n ',747,4,4,2
8333,Sea Point,'\n\n 8\700\000\n ',None,2,2,2
8334,Pinelands,'\n\n 617\079\n ',20,1,1,1
8335,Rondebosch,'\n\n 1\985\000\n ',None,None,None,None
8336,Sea Point,'\n\n 4\250\000\n ',178,2,2,None
8337,Cape Town City Centre,'\n\n 1\750\000\n ',57,1,1,1
8338,Plumstead,'\n\n 2\295\000\n ',497,2.5,4,6
8339,Camps Bay,'\n\n 33\925\000\n ',456,3.5,3,None
8340,Pelican Park,'\n\n 440\000\n ',None,1,2,None
8341,Woodstock,'\n\n 1\350\000\n ',120,1,2,None
8342,Newlands,'\n\n 3\950\000\n ',534,1,3,6
8343,De Waterkant,'\n\n 2\950\000\n ',50,1,1,1
8344,Sea Point,'\n\n 2\880\000\n ',47,1,2,1
8345,Green Point,'\n\n 3\495\000\n ',110,1,3,2
8346,Kenilworth,'\n\n 3\590\000\n ',247,2,3,3
8347,Cape Town City Centre,'\n\n 2\400\000\n ',63,2,2,None
8348,Pinelands,'\n\n 595\000\n ',None,1,None,None
8349,De Waterkant,'\n\n 4\950\000\n ',73,2,2,2
8350,Pelican Park,'\n\n 850\000\n ',201,None,None,None
8351,Diep River,'\n\n 2\342\107\n ',None,1,2,1
8352,Sea Point,'\n\n 1\275\000\n ',24,1,1,None
8353,Cape Town City Centre,'\n\n 1\925\000\n ',35,1,1,1
8354,Vredehoek,'\n\n 2\995\000\n ',100,1,3,None
8355,Lansdowne,'\n\n 3\200\000\n ',934,None,None,None
8356,Zonnebloem,'\n\n 950\000\n ',None,1,1,None
8357,De Waterkant,'\n\n 2\999\000\n ',None,1,1,1
8358,None,None,None,None,None,None

In [445]:
import re
final['price'] = final['price'].apply(lambda x: re.sub("[^0-9]", "",x))

/home/cate/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [446]:
final

"(index, )",location,price,floor_size,bathrooms,bedrooms,parking
1,Green Point,8750000,175,2,2,2
2,Sea Point,15999000,300,4.5,4,2
3,Observatory,1900000,65,2,2,1
4,Bantry Bay,18995000,159,2,2,1
5,Ottery,5800000,803,10,10,8
6,Wynberg Upper,5550000,918,4,4,2
7,Cape Town City Centre,2290000,106,1.5,1,1
8,Constantia,19900000,1 437,5.5,5,7
9,Kenilworth,1875000,82,1.5,2,2
10,Wynberg Upper,2800000,712,3,3,4
11,Sea Point,4250000,178,2,2,2
12,Claremont,1699000,130,1,2,2
13,Vredehoek,1450000,42,1,1,1
14,Wynberg Upper,3750000,100,2,2,2
15,Constantia,5950000,1 561,2.5,4,5
16,Kenilworth,1850000,104,1,2,2
17,Marina Da Gama,1590000,174,2,2,2
18,Bergvliet,3895000,862,3,3,7
19,Newlands,5900000,628,2.5,3,2
20,Bantry Bay,13000000,149,2,2,1
21,Sea Point,2150000,81,1,2,None
22,Sea Point,2800000,None,2,2,None
23,Muizenberg,2793000,402,2,4,None
24,Constantia,5150000,792,2,4,4
25,Green Point,1750000,51,1,None,None
26,Bantry Bay,12950000,151,2,3,1
27,Claremont Upper,1595000,74,1,2,1
28,Mouille Point,7500000,91,1,2,1
29,Lakeside,3499000,659,2,3,5
30,Maitland,810000,54,1,2,None
...,...,...,...,...,...,...
8329,Cape Town City Centre,8850000,297,3.5,3,2
8330,Woodstock,1695000,57,1,1,1
8331,Sea Point,2900000,87,1,2,None
8332,Camps Bay,24975000,747,4,4,2
8333,Sea Point,8700000,None,2,2,2
8334,Pinelands,617079,20,1,1,1
8335,Rondebosch,1985000,None,None,None,None
8336,Sea Point,4250000,178,2,2,None
8337,Cape Town City Centre,1750000,57,1,1,1
8338,Plumstead,2295000,497,2.5,4,6
8339,Camps Bay,33925000,456,3.5,3,None
8340,Pelican Park,440000,None,1,2,None
8341,Woodstock,1350000,120,1,2,None
8342,Newlands,3950000,534,1,3,6
8343,De Waterkant,2950000,50,1,1,1
8344,Sea Point,2880000,47,1,2,1
8345,Green Point,3495000,110,1,3,2
8346,Kenilworth,3590000,247,2,3,3
8347,Cape Town City Centre,2400000,63,2,2,None
8348,Pinelands,595000,None,1,None,None
8349,De Waterkant,4950000,73,2,2,2
8350,Pelican Park,850000,201,None,None,None
8351,Diep River,2342107,None,1,2,1
8352,Sea Point,1275000,24,1,1,None
8353,Cape Town City Centre,1925000,35,1,1,1
8354,Vredehoek,2995000,100,1,3,None
8355,Lansdowne,3200000,934,None,None,None
8356,Zonnebloem,950000,None,1,1,None
8357,De Waterkant,2999000,None,1,1,1
8358,None,,None,None,None,None

In [451]:
final.to_csv("/home/cate/Cate/DSI/DSI_trick_challenge/final_cleaner.csv", index = False)